(
 (nil . ((indent-tabs-mode . nil)))
 (prog-mode . ((fill-column . 95)))
 (c-mode . ((c-basic-offset . 2)
            (c-block-comment-prefix . "")
            (comment-start . "// ")
            (comment-end . "")
            (c-file-offsets . ((statement-cont . c-lineup-math)
                               (substatement-open . 0)
                               (arglist-intro . +)
                               (inline-open . 0)
                               (case-label . *)
                               (statement-case-open . *)
                               (label . *)
                               (statement-case-intro . *)
                               (inextern-lang . 0)
                               (inlambda . 0) ; c-lineup-inexpr-block
                               (innamespace . 0)
                               (access-label . /)))))
 ;; Is there a way to not duplicate this?
 (c++-mode . ((c-basic-offset . 2)
              (c-block-comment-prefix . "")
              (comment-start . "// ")
              (comment-end . "")
              (c-file-offsets . ((statement-cont . c-lineup-math)
                                 (substatement-open . 0)
                                 (arglist-intro . +)
                                 (inline-open . 0)
                                 (case-label . *)
                                 (statement-case-open . *)
                                 (label . *)
                                 (statement-case-intro . *)
                                 (inextern-lang . 0)
                                 (inlambda . 0) ; c-lineup-inexpr-block
                                 (innamespace . 0)
                                 (access-label . /)))))
 (java-mode . ((c-basic-offset . 2)))
 (prolog-mode . ((prolog-indent-width . 4)))
 (".git" . ((nil . ((fill-column . 72)))))
)
