// This file was automatically generated by collect-hashes.py
#ifndef __KNOWN_HASHES_HPP
#define __KNOWN_HASHES_HPP
#include <string>
#include <vector>
namespace {
struct hashinfo {
  std::string hash;
  std::string demangled_name;
  std::string mangled_name;
  std::string classification;
};
static std::vector<hashinfo> known_hashes = {
// 0x405f95 in ../code/testcases/firefox/firefox.exe
{"461DC4B8600ED566F713991B1375A37B", "near near void * __cdecl operator new[](unsigned int) ", "??_U@YAPAXI@Z", "new[]"},
// 0x45fe20 in ../code/testcases/BuildExes/BuildExesvs2017/vs2017/sc0d0o0/Debug/oopoly.exe
{"73550BF1A49A752D459EF87DFFD9355F", "__purecall", "__purecall", "purecall"},
// 0x40177c in ../code/testcases/BuildExes/BuildExesvs2012/vs2012/sc1d1o0/RelWithDebInfo/ooex8.exe
{"9DC4BC4528E40C444E04C1D2F340867F", "near near void * __cdecl operator new(unsigned int) ", "??2@YAPAXI@Z", "new"},
// 0x41c12d in ../code/testcases/firefox/firefox.exe
{"E12D5839514E066C8559A2E92943817C", "near void __cdecl operator delete(near void *, enum sandbox::AllocationType) ", "??3@YAXPAXW4AllocationType@sandbox@@@Z", "delete"},
// 0x427b84 in ../code/testcases/BuildExes/BuildExesvs2008/vs2008/dc0d0o1/Debug/ooex7.exe
{"647037DC779B0E198057D5F7819CE63F", "__purecall", "__purecall", "purecall"},
// 0x45bd00 in ../code/testcases/BuildExes/BuildExesvs2015/vs2015/sc0d0o0/Debug/oopoly.exe
{"F22CB8376BF17CA45FFD536D76ABBCF1", "__purecall", "__purecall", "purecall"},
// 0x436be0 in ../code/testcases/BuildExes/BuildExesvs2010/vs2010/sc0d0o0/Debug/oo.exe
{"1467148241C4F9AC1F6E2884134CB170", "near void __cdecl operator delete(near void *, near void *) ", "??3@YAXPAX0@Z", "del placement"},
// 0x10129fb3 in ../code/testcases/malware/malware-deb6a7a1a806ca372a56944efa4601ee.exe
{"88F7AC7E86D87DCCFD20025B18EA0F44", "near near void * __cdecl operator new(unsigned int, near void *) ", "??2@YAPAXIPAX@Z", "new placement"},
// 0x404160 in ../code/testcases/BuildExes/BuildExesvs2012/vs2012/dc0d0o0/Debug/oonewdel.exe
{"9EB2A996ED6C58F7E4B28BEC7C4B1936", "near near void * __cdecl operator new(unsigned int, near struct std::nothrow_t const &) ", "??2@YAPAXIABUnothrow_t@std@@@Z", "new nothrow"},
// 0x41eebe in ../code/testcases/PicoHttp/ep_srv.exe
{"9F377A6D9EDE41E4F1B43C475069EE28", "near near void * __cdecl operator new(unsigned int) ", "??2@YAPAXI@Z", "new"},
// 0x4565d0 in ../code/testcases/TinyXml/tinyXmlTest-NewDebug.exe
{"7C14E35CB0E52838CFE0A7E3A78CA65B", "near near void * __cdecl operator new[](unsigned int) ", "??_U@YAPAXI@Z", "new[]"},
// 0x404940 in ../code/testcases/BuildExes/BuildExesvs2017/vs2017/dc0d0o1/Debug/oonewdel.exe
{"561CCB32DF7C5A53A2B7D76202044B64", "near near void * __cdecl operator new(unsigned int, enum std::align_val_t, near struct std::nothrow_t const &) ", "??2@YAPAXIW4align_val_t@std@@ABUnothrow_t@1@@Z", "new nothrow align"},
// 0x48b650 in ../code/testcases/malware/malware-29be5a337b33bd4c3e14a695dc038dc3.exe
{"616923B4D7B8A5204A54F61C663C984D", "__purecall", "__purecall", "purecall"},
// 0x456470 in ../code/testcases/TinyXml/tinyXmlTest-NewDebug.exe
{"6F75265BD0A85F09873731BF5AA734A3", "near void __cdecl operator delete[](near void *) ", "??_V@YAXPAX@Z", "del[]"},
// 0x40a830 in ../code/testcases/BuildExes/BuildExesvs2012/vs2012/sc0d0o0/Debug/oopoly.exe
{"5FA3DAE16B3C816760BA346D28B362AC", "near near void * __cdecl operator new(unsigned int, near struct std::_DebugHeapTag_t const &, near char *, int) ", "??2@YAPAXIABU_DebugHeapTag_t@std@@PADH@Z", "new debug"},
// 0x411f00 in ../code/testcases/BuildExes/BuildExesvs2010/vs2010/dc0d0o0/Debug/oonewdel.exe
{"021DB8DE05126FAE53CB1DBC05561B78", "near void __cdecl operator delete(near void *, int, near char const *, int) ", "??3@YAXPAXHPBDH@Z", "del debug"},
// 0x41f30a in ../code/testcases/PicoHttp/ep_srv.exe
{"0CF963B9B193252F2CDEC4159322921B", "__purecall", "__purecall", "purecall"},
// 0x4041e0 in ../code/testcases/BuildExes/BuildExesvs2012/vs2012/dc0d0o0/Debug/oonewdel.exe
{"2E86BF8F392A42C8EE4ECF33943E5BBC", "near near void * __cdecl operator new[](unsigned int, near struct std::nothrow_t const &) ", "??_U@YAPAXIABUnothrow_t@std@@@Z", "new[] nothrow"},
// 0x41ee41 in ../code/testcases/PicoHttp/ep_srv.exe
{"3D3F9E46688A1687E2AB372921A31394", "near void __cdecl operator delete(near void *) ", "??3@YAXPAX@Z", "del"},
// 0x415b60 in ../code/testcases/light-pop3-smtp/pop3.exe
{"443BABE6802D856C2EF32B80CD14B474", "near near void * __cdecl operator new(unsigned int, near void *) ", "??2@YAPAXIPAX@Z", "new placement"},
// 0x48c0a0 in ../code/testcases/CImg/tetris.exe
{"9A4E8AEC15BFD15176C05D34AACEB8CE", "near near void * __cdecl operator new(unsigned int, near class _HeapManager &, int) ", "??2@YAPAXIAAV_HeapManager@@H@Z", "new unknown_heapmanager"},
// 0x401231 in ../code/testcases/BuildExes/BuildExesvs2013/vs2013/sc0d0o0/RelWithDebInfo/ooex4.exe
{"8BF32924D9F4199C4B35410EC797D180", "near near void * __cdecl operator new(unsigned int) ", "??2@YAPAXI@Z", "new"},
// 0x401a53 in ../code/testcases/BuildExes/BuildExesvs2008/vs2008/dc0d0o1/Debug/oonewdel.exe
{"1F25BCD5FAF0B9594CFCB42EAEAE99F6", "near void __cdecl operator delete[](near void *, near struct std::nothrow_t const &) ", "??_V@YAXPAXABUnothrow_t@std@@@Z", "del[] nothrow"},
// 0x41c170 in ../code/testcases/PicoHttp/ep_srv.exe
{"9BD1ED0583316F4F3679B990217F0BC7", "near void __cdecl operator delete(near void *, near void *) ", "??3@YAXPAX0@Z", "del placement"},
// 0x4850f4 in ../code/testcases/mysql/mysql.exe
{"D6889BB6AC79482E1EDABB23CF0F194C", "near near void * __cdecl operator new(unsigned int, near struct std::nothrow_t const &) ", "??2@YAPAXIABUnothrow_t@std@@@Z", "new nothrow"},
// 0x40a870 in ../code/testcases/BuildExes/BuildExesvs2012/vs2012/sc0d0o0/Debug/oopoly.exe
{"DFA731C74D9EF0BE8E85EA1D36B56B3C", "near void __cdecl operator delete(near void *, near struct std::_DebugHeapTag_t const &, near char *, int) ", "??3@YAXPAXABU_DebugHeapTag_t@std@@PADH@Z", "del debug"},
// 0x4402a0 in ../code/testcases/BuildExes/BuildExesvs2012/vs2012/sc0d0o0/Debug/oopoly.exe
{"6040FB1A8C43146322C12F6FEDB78351", "near near void * __cdecl operator new(unsigned int) ", "??2@YAPAXI@Z", "new"},
// 0x4407f0 in ../code/testcases/BuildExes/BuildExesvs2012/vs2012/sc0d1o1/Debug/oo.exe
{"8D4762ABA02E949F19752C2E511A98E7", "near void __cdecl operator delete(near void *) ", "??3@YAXPAX@Z", "del"},
// 0x412a70 in ../code/testcases/VisualCppTests/LoopTest/LoopTest.exe
// See github issue #151
//// 0x4fb6e0 in ../code/testcases/malware/malware-67b9be3c70653a48a239a380e697babc.exe
//{"7461553B7014A7921AC39DBA12CCC3A7", "near near void * __cdecl operator new[](unsigned int) ", "??_U@YAPAXI@Z", "new[]"},
// 0x415ba0 in ../code/testcases/light-pop3-smtp/pop3.exe
{"73F3C7EF29364905D2D9B95F19640509", "near void __cdecl operator delete(near void *, near void *) ", "??3@YAXPAX0@Z", "del placement"},
// 0x46b780 in ../code/testcases/BuildExes/BuildExesvs2012/vs2012/sc0d0o0/Debug/oopoly.exe
{"865EFC75449456AA06F91D0E87577961", "near near void * __cdecl operator new(unsigned int, near class _HeapManager &, int) ", "??2@YAPAXIAAV_HeapManager@@H@Z", "new unknown_heapmanager"},
// 0x439110 in ../code/testcases/BuildExes/BuildExesvs2010/vs2010/sc0d0o0/Debug/oo.exe
{"6E2BED9FC03D0065BEFA589018BE7BDF", "near near void * __cdecl operator new(unsigned int, near struct std::_DebugHeapTag_t const &, near char *, int) ", "??2@YAPAXIABU_DebugHeapTag_t@std@@PADH@Z", "new debug"},
// 0x401d64 in ../code/testcases/BuildExes/BuildExesvs2017/vs2017/dc0d0o1/RelWithDebInfo/oonewdel.exe
{"9631DB10B1076E70397C3D6E4CE875A0", "near near void * __cdecl operator new(unsigned int, enum std::align_val_t) ", "??2@YAPAXIW4align_val_t@std@@@Z", "new align"},
// 0x410a5c in ../code/testcases/BuildExes/BuildExesvs2017/vs2017/sc0d0o0/RelWithDebInfo/ooex2.exe
{"303A66CFA9FA2B66959D1C4DFCC95C93", "__purecall", "__purecall", "purecall"},
// 0x406405 in ../code/testcases/firefox/firefox.exe
{"3D01B1E1279476F6FFA9296C4E387579", "near void __cdecl operator delete(near void *, unsigned int) ", "??3@YAXPAXI@Z", "del"},
// 0x41c160 in ../code/testcases/PicoHttp/ep_srv.exe
{"E281C55328CFE7231BB4573A1C7CE0FA", "near near void * __cdecl operator new(unsigned int, near void *) ", "??2@YAPAXIPAX@Z", "new placement"},
// 0x405fa0 in ../code/testcases/BuildExes/BuildExesvs2012/vs2012/sc0d0o0/Debug/oonewdel.exe
{"AA10C27998BF6C88336CA08958356D85", "near near void * __cdecl operator new(unsigned int, int, near char const *, int) ", "??2@YAPAXIHPBDH@Z", "new debug"},
// 0x401a84 in ../code/testcases/BuildExes/BuildExesvs2008/vs2008/dc0d0o1/Debug/oonewdel.exe
{"CC883629B7DB64E925D711EC971B8FCA", "near near void * __cdecl operator new(unsigned int, near struct std::nothrow_t const &) ", "??2@YAPAXIABUnothrow_t@std@@@Z", "new nothrow"},
// 0x401db6 in ../code/testcases/BuildExes/BuildExesvs2017/vs2017/dc0d0o1/RelWithDebInfo/oonewdel.exe
{"6B0F7C090029A07D7778F59496173246", "near void __cdecl operator delete(near void *, unsigned int, enum std::align_val_t) ", "??3@YAXPAXIW4align_val_t@std@@@Z", "del align"},
// 0x402450 in ../code/testcases/log4cpp/testMain-Release.exe
{"D78276F56F8EC8D4F8CCA375E4534366", "near void __cdecl operator delete(near void *, near void *) ", "??3@YAXPAX0@Z", "del placement"},
// 0x405f5d in ../code/testcases/firefox/firefox.exe
{"76CECF37598DEFEE4EB5C788775AB032", "near near void * __cdecl operator new(unsigned int) ", "??2@YAPAXI@Z", "new"},
// 0x4a2510 in ../code/testcases/CImg/tetris.exe
{"1DE1A7D4D8674BC64CB82BD8402BC314", "__purecall", "__purecall", "purecall"},
// 0x413050 in ../code/testcases/BuildExes/BuildExesvs2010/vs2010/dc0d0o0/Debug/oonewdel.exe
{"A79C3EFA7C39EBB3C8345E63E31EF315", "near near void * __cdecl operator new[](unsigned int, near struct std::nothrow_t const &) ", "??_U@YAPAXIABUnothrow_t@std@@@Z", "new[] nothrow"},
// 0x439220 in ../code/testcases/BuildExes/BuildExesvs2010/vs2010/sc0d0o0/Debug/oo.exe
{"A4A4B36BC2681D1F40228DC285198486", "near void __cdecl operator delete(near void *, near struct std::_DebugHeapTag_t const &, near char *, int) ", "??3@YAXPAXABU_DebugHeapTag_t@std@@PADH@Z", "del debug"},
// 0x42b620 in ../code/testcases/BuildExes/BuildExesvs2010/vs2010/sc0d0o0/Debug/oonewdel.exe
{"67D6CA9FA309C0764C792F460E1AD73C", "near near void * __cdecl operator new(unsigned int, int, near char const *, int) ", "??2@YAPAXIHPBDH@Z", "new debug"},
// 0x405f90 in ../code/testcases/firefox/firefox.exe
{"12C3EBBDA814F751A0EBE967631BABC8", "near void __cdecl operator delete(near void *) ", "??3@YAXPAX@Z", "del"},
// 0x4048f0 in ../code/testcases/BuildExes/BuildExesvs2015/vs2015/dc0d0o1/Debug/oonewdel.exe
{"A59BF6BF2B331BEB7F1785F4C86A308F", "near near void * __cdecl operator new(unsigned int, near struct std::nothrow_t const &) ", "??2@YAPAXIABUnothrow_t@std@@@Z", "new nothrow"},
// 0x413fbd in ../code/testcases/BuildExes/BuildExesvs2015/vs2015/sc0d0o0/RelWithDebInfo/oonewdel.exe
{"A40E07798B9C45F925A4D36D501B22D8", "__purecall", "__purecall", "purecall"},
// 0x401e67 in ../code/testcases/BuildExes/BuildExesvs2017/vs2017/dc0d0o1/RelWithDebInfo/oonewdel.exe
{"7F00628AD4C76383E3B76825C462D97B", "near near void * __cdecl operator new(unsigned int, enum std::align_val_t, near struct std::nothrow_t const &) ", "??2@YAPAXIW4align_val_t@std@@ABUnothrow_t@1@@Z", "new nothrow align"},
// 0x431889 in ../code/testcases/PicoHttp/ep_srv.exe
{"B73F80840760DCF5D239C580272BA6E2", "near near void * __cdecl operator new(unsigned int, near class _HeapManager &, int) ", "??2@YAPAXIAAV_HeapManager@@H@Z", "new unknown_heapmanager"},
// 0x424b24 in ../code/testcases/BuildExes/BuildExesvs2013/vs2013/sc0d0o0/RelWithDebInfo/oo.exe
{"E7FD44AB8DB4BE5CA317C517B9C47CF1", "near near void * __cdecl operator new(unsigned int) ", "??2@YAPAXI@Z", "new"},
// 0x405ff0 in ../code/testcases/BuildExes/BuildExesvs2012/vs2012/sc0d0o0/Debug/oonewdel.exe
{"6D830994392959D8964A8699F8344031", "near near void * __cdecl operator new[](unsigned int, int, near char const *, int) ", "??_U@YAPAXIHPBDH@Z", "new[] debug"},
// 0x401d6e in ../code/testcases/BuildExes/BuildExesvs2015/vs2015/dc0d0o1/RelWithDebInfo/oonewdel.exe
{"71753574DCD61824BA6F64CE3478E17C", "near near void * __cdecl operator new(unsigned int, near struct std::nothrow_t const &) ", "??2@YAPAXIABUnothrow_t@std@@@Z", "new nothrow"},
// 0x4106b0 in ../code/testcases/BuildExes/BuildExesvs2019/vs2019/sc0d0o0/Debug/ooex0.exe
{"C57BCCA380E7272E4121376A1A4E82C2", "near near void * __cdecl operator new(unsigned int, near class _HeapManager &, int) ", "??2@YAPAXIAAV_HeapManager@@H@Z", "new unknown_heapmanager"},
// 0x413070 in ../code/testcases/BuildExes/BuildExesvs2010/vs2010/dc0d0o0/Debug/oonewdel.exe
{"F51197FED07B44B5A94BA159A148928F", "near near void * __cdecl operator new(unsigned int, near struct std::nothrow_t const &) ", "??2@YAPAXIABUnothrow_t@std@@@Z", "new nothrow"},
// 0x401b30 in ../code/testcases/BuildExes/BuildExesvs2015/vs2015/dc0d0o1/Debug/ooex9.exe
{"E34CEDB1A0A02AA76173BA4A52CAB822", "near void __cdecl operator delete(near void *) ", "??3@YAXPAX@Z", "del"},
// 0x440230 in ../code/testcases/BuildExes/BuildExesvs2012/vs2012/sc0d0o0/Debug/oopoly.exe
{"C8CE53E8E44E37BD622BD42222DCE0EC", "__purecall", "__purecall", "purecall"},
// 0x401ad0 in ../code/testcases/BuildExes/BuildExesvs2015/vs2015/dc0d0o1/Debug/ooex9.exe
{"BACD68267934497D17B3D6E22A7C8425", "near near void * __cdecl operator new(unsigned int) ", "??2@YAPAXI@Z", "new"},
// 0x4047e0 in ../code/testcases/BuildExes/BuildExesvs2017/vs2017/dc0d0o1/Debug/oonewdel.exe
{"7EEED9262F87AA960FC61F8AAAC7F075", "near void __cdecl operator delete(near void *, unsigned int, enum std::align_val_t) ", "??3@YAXPAXIW4align_val_t@std@@@Z", "del align"},
// 0x42b700 in ../code/testcases/BuildExes/BuildExesvs2010/vs2010/sc0d0o0/Debug/oonewdel.exe
{"64A84305849D9D0BE912EE145B34EB7D", "near near void * __cdecl operator new[](unsigned int, int, near char const *, int) ", "??_U@YAPAXIHPBDH@Z", "new[] debug"},
// 0x409ffc in ../code/testcases/BuildExes/BuildExesvs2008/vs2008/dc0d0o1/Debug/ooex7.exe
{"27441D7519FDC00A6560789EDFA55442", "near near void * __cdecl operator new(unsigned int) ", "??2@YAPAXI@Z", "new"},
// 0x40119e in ../code/testcases/BuildExes/BuildExesvs2013/vs2013/sc0d0o0/RelWithDebInfo/ooex4.exe
{"77DCB831A61DB2C547210E6D81AC47DA", "__purecall", "__purecall", "purecall"},
// 0x401060 in ../code/testcases/muparser/example1-Release.exe
{"6430114819AFF53F9F8663821F537E0B", "near near void * __cdecl operator new(unsigned int, near void *) ", "??2@YAPAXIPAX@Z", "new placement"},
// 0x40aa24 in ../code/testcases/BuildExes/BuildExesvs2012/vs2012/sc0d0o0/RelWithDebInfo/oonewdel.exe
{"3DA7CB537344A45D8D5AA4F8DCBD4723", "near near void * __cdecl operator new(unsigned int, near class _HeapManager &, int) ", "??2@YAPAXIAAV_HeapManager@@H@Z", "new unknown_heapmanager"},
// 0x451920 in ../code/testcases/CImg/tetris.exe
{"AF1F2D507A61BD061C263EA118E002B1", "near void __cdecl operator delete(near void *) ", "??3@YAXPAX@Z", "del"},
// 0x439240 in ../code/testcases/BuildExes/BuildExesvs2010/vs2010/sc0d0o0/Debug/oo.exe
{"FABE858E2BC9046E9C0B70F3E16B00F1", "near void __cdecl operator delete[](near void *, near struct std::_DebugHeapTag_t const &, near char *, int) ", "??_V@YAXPAXABU_DebugHeapTag_t@std@@PADH@Z", "del[] debug"},
// 0x40a890 in ../code/testcases/BuildExes/BuildExesvs2012/vs2012/sc0d0o0/Debug/oopoly.exe
{"F40EB89441DA7492685D534CA793D285", "near near void * __cdecl operator new[](unsigned int, near struct std::_DebugHeapTag_t const &, near char *, int) ", "??_U@YAPAXIABU_DebugHeapTag_t@std@@PADH@Z", "new[] debug"},
// 0x404760 in ../code/testcases/BuildExes/BuildExesvs2017/vs2017/dc0d0o1/Debug/oonewdel.exe
{"73D61AF7F87993703EB50D155B1ED330", "near near void * __cdecl operator new(unsigned int, enum std::align_val_t) ", "??2@YAPAXIW4align_val_t@std@@@Z", "new align"},
// 0x401df8 in ../code/testcases/BuildExes/BuildExesvs2017/vs2017/dc0d0o1/RelWithDebInfo/oonewdel.exe
{"5FDA4A8152AC1A383FA94E38BC67DD12", "near near void * __cdecl operator new(unsigned int, near struct std::nothrow_t const &) ", "??2@YAPAXIABUnothrow_t@std@@@Z", "new nothrow"},
// 0x4402f0 in ../code/testcases/BuildExes/BuildExesvs2012/vs2012/sc0d0o0/Debug/oopoly.exe
{"461573DBE9B320C700B59046D484E769", "near void __cdecl operator delete(near void *) ", "??3@YAXPAX@Z", "del"},
// 0x40c12f in ../code/testcases/BuildExes/BuildExesvs2019/vs2019/sc0d0o0/RelWithDebInfo/oonewdel.exe
{"0C29AA98731295E20BCDFDEF8FEC280F", "near near void * __cdecl operator new(unsigned int, near class _HeapManager &, int) ", "??2@YAPAXIAAV_HeapManager@@H@Z", "new unknown_heapmanager"},
// 0x451b20 in ../code/testcases/CImg/tetris.exe
{"C52CE447F503B93E07837633DA311E66", "near near void * __cdecl operator new(unsigned int) ", "??2@YAPAXI@Z", "new"},
// 0x401c69 in ../code/testcases/BuildExes/BuildExesvs2017/vs2017/dc0d0o1/RelWithDebInfo/ooex7.exe
{"09669E4F4CAC6FDA60E63018CBD0EDAF", "near near void * __cdecl operator new(unsigned int) ", "??2@YAPAXI@Z", "new"},
// 0x4049b0 in ../code/testcases/BuildExes/BuildExesvs2015/vs2015/dc0d0o1/Debug/oonewdel.exe
{"A01879CE6CC3665A9A887DA0F9D66BA2", "near near void * __cdecl operator new(unsigned int, int, near char const *, int) ", "??2@YAPAXIHPBDH@Z", "new debug"},
// 0x41c0f7 in ../code/testcases/firefox/firefox.exe
{"434EED35048ED13EA0F9A516724587AF", "near near void * __cdecl operator new(unsigned int, enum sandbox::AllocationType, near void *) ", "??2@YAPAXIW4AllocationType@sandbox@@PAX@Z", "new"},
// 0x403009 in ../code/testcases/BuildExes/BuildExesvs2012/vs2012/sc0d0o0/RelWithDebInfo/oonewdel.exe
{"5E0B334DD553FCE5F2DE0FDDB66D6174", "near near void * __cdecl operator new(unsigned int) ", "??2@YAPAXI@Z", "new"},
};
}
#endif
