function(add_cxx_compiler_flags)
  include(CheckCXXCompilerFlag)
  set(flags ${CMAKE_CXX_FLAGS})
  foreach(flag ${ARGV})
    check_cxx_compiler_flag("${flag}" works)
    if(works)
      set(flags "${flags} ${flag}")
    endif()
  endforeach()
  set(CMAKE_CXX_FLAGS ${flags} PARENT_SCOPE)
endfunction()
